### ISSUE TITLE
Adding to toml's Implementations wiki 

### ISSUE THREAD

**Issue by prime167** [SamboyCoding/Tomlet#3]
Thank you for your hard work. Currently, there is no v1.0.0 compliant in .NET, Can you please add this to the [wiki](https://github.com/toml-lang/toml/wiki#implementations)?

**Comment by SamboyCoding** [comment]
Hi! I would like a little further confirmation that I *am* fully compliant before declaring so in the Wiki. Everything I have personally tested seems to work, but I would like a few more opiniolns. If you can confirm this is the case, I will be happy to do so.

**Comment by prime167** [comment]
Ok, that make sense. It will be great for .NET community

**Comment by SamboyCoding** [comment]
Somebody else has already done this, so I'm closing this issue.
