### ISSUE TITLE
Keys with symbols aren't quoted but they should be

### ISSUE THREAD

**Issue by ThatCoolCoder** [SamboyCoding/Tomlet#30]
I have a dictionary like so:
```c#
var obj = new Dictionary<string, string>()
{
    {"normal-key", "value for normal key"},
    {"key with spaces", "value for key with spaces"},
    {"key!with{}(*%&)random[other+symbols", "value for key with random other symbols"},
    {"key/with/slashes", "value for key with slashes"},
};
```
And I'm saving it with `TomletMain.TomlStringFrom(obj);`, but some of the keys in the output are not quoted even though they should be:
```toml
normal-key = "value for normal key" # correctly not quoted
"key with spaces" = "value for key with spaces" # correctly quoted
key!with{}(*%&)random[other+symbols = "value for key with random other symbols" # should be quoted but isn't
key/with/slashes = "value for key with slashes" # should be quoted but isn't
```

Now this isn't actually causing a problem for me currently since the only non-alphanumeric characters in my keys are forward slashes (which Tomlet can read back just fine), but technically this is against the toml spec and would cause issues with other characters.

Also, I get a `Tomlet.Exceptions.TomlNoSuchValueException` if I try having dictionary keys with full stops in them, but I don't know if that's a problem with this library or if that's against the toml spec.

**Comment by SamboyCoding** [comment]
The dictionary keys with full stops thing actually is a confusing-enough point that there's a paragraph or so on it https://github.com/SamboyCoding/Tomlet#a-word-on-dotted-keys
